Parameters:
  BootstrapVersion:
    Type:                               AWS::SSM::Parameter::Value<String>
    Default:                            /cdk-bootstrap/hnb659fds/version
    Description:                        Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]


Resources:

  ##
  ## AppsyncDynamodbStack / TasksTable / Resource
  ##

  TasksTable:
    Type:                               AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName:                id
          AttributeType:                S
      BillingMode:                      PAY_PER_REQUEST
      KeySchema:
        - AttributeName:                id
          KeyType:                      HASH
      TableName:                        tasks
    DeletionPolicy:                     Delete
    UpdateReplacePolicy:                Delete
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/TasksTable/Resource

  ##
  ## AppsyncDynamodbStack / TaskApi / Resource
  ##

  TaskApi:
    Type:                               AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType:               API_KEY
      Name:                             task-api
      XrayEnabled:                      true
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/TaskApi/Resource

  ##
  ## AppsyncDynamodbStack / TaskApi / Schema
  ##

  TaskApiSchema:
    Type:                               AWS::AppSync::GraphQLSchema
    Properties:
      ApiId:                            !GetAtt TaskApi.ApiId
      Definition:                       |-
                                        type Task {
                                          id: ID!
                                          title: String!
                                          description: String
                                          completed: Boolean!
                                          createdAt: AWSDateTime!
                                        }
                                        
                                        type Query {
                                          getTask(id: ID!): Task
                                          listTasks: [Task!]!
                                        }
                                        
                                        type Mutation {
                                          createTask(title: String!, description: String): Task!
                                          updateTask(id: ID!, title: String, description: String, completed: Boolean): Task!
                                          deleteTask(id: ID!): Task
                                        }
                                        
                                        schema {
                                          query: Query
                                          mutation: Mutation
                                        }
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/TaskApi/Schema

  ##
  ## AppsyncDynamodbStack / TaskApi / DefaultApiKey
  ##

  TaskApiDefaultApiKey:
    Type:                               AWS::AppSync::ApiKey
    Properties:
      ApiId:                            !GetAtt TaskApi.ApiId
    DependsOn:
      -                                 TaskApiSchema
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/TaskApi/DefaultApiKey

  ##
  ## AppsyncDynamodbStack / TaskApi / TasksDataSource / ServiceRole / Resource
  ##

  TasksDataSourceRole:
    Type:                               AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
        Version: '2012-10-17'
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/TaskApi/TasksDataSource/ServiceRole/Resource

  ##
  ## AppsyncDynamodbStack / TaskApi / TasksDataSource / ServiceRole / DefaultPolicy / Resource
  ##

  ServiceRolePolicy:
    Type:                               AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - !GetAtt TasksTable.Arn
              - !Ref AWS::NoValue
        Version: '2012-10-17'
      PolicyName:                       ServiceRolePolicy
      Roles:
        - !Ref TasksDataSourceRole
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/TaskApi/TasksDataSource/ServiceRole/DefaultPolicy/Resource

  ##
  ## AppsyncDynamodbStack / TaskApi / TasksDataSource / Resource
  ##

  TaskApiTasksDataSource:
    Type:                               AWS::AppSync::DataSource
    Properties:
      ApiId:                            !GetAtt TaskApi.ApiId
      DynamoDBConfig:
        AwsRegion: !Ref AWS::Region
        TableName: !Ref TasksTable
      Name:                             TasksDataSource
      ServiceRoleArn:                   !GetAtt TasksDataSourceRole.Arn
      Type:                             AMAZON_DYNAMODB
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/TaskApi/TasksDataSource/Resource

  ##
  ## AppsyncDynamodbStack / GetTaskFunction / Resource
  ##

  GetTaskFunction:
    Type:                               AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId:                            !GetAtt TaskApi.ApiId
      CodeS3Location:                   !Sub s3://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}/5e9e6d835092db8af2bf65534aac87dc0c9bbd633e7ccbf1b3af3f70ed17dc15.js
      DataSourceName:                   TasksDataSource
      FunctionVersion:                  '2018-05-29'
      Name:                             getTask
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
    DependsOn:
      -                                 TaskApiSchema
      -                                 TaskApiTasksDataSource
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/GetTaskFunction/Resource

  ##
  ## AppsyncDynamodbStack / ListTasksFunction / Resource
  ##

  ListTasksFunction:
    Type:                               AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId:                            !GetAtt TaskApi.ApiId
      CodeS3Location:                   !Sub s3://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}/aa4602820917070afb8fec3310f27a3eaf8fa27ea1ec8f72c04f3b417ef24917.js
      DataSourceName:                   TasksDataSource
      FunctionVersion:                  '2018-05-29'
      Name:                             listTasks
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
    DependsOn:
      -                                 TaskApiSchema
      -                                 TaskApiTasksDataSource
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/ListTasksFunction/Resource

  ##
  ## AppsyncDynamodbStack / GetTaskResolver / Resource
  ##

  GetTaskResolver:
    Type:                               AWS::AppSync::Resolver
    Properties:
      ApiId:                            !GetAtt TaskApi.ApiId
      CodeS3Location:                   !Sub s3://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}/fc2971de5d01be163d5876782ad6d22b9f3dccc00030222599c3b8e473b115a3.js
      FieldName:                        getTask
      Kind:                             PIPELINE
      PipelineConfig:
        Functions:
          - !GetAtt GetTaskFunction.FunctionId
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
      TypeName:                         Query
    DependsOn:
      -                                 TaskApiSchema
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/GetTaskResolver/Resource

  ##
  ## AppsyncDynamodbStack / ListTasksResolver / Resource
  ##

  ListTasksResolver:
    Type:                               AWS::AppSync::Resolver
    Properties:
      ApiId:                            !GetAtt TaskApi.ApiId
      CodeS3Location:                   !Sub s3://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}/fc2971de5d01be163d5876782ad6d22b9f3dccc00030222599c3b8e473b115a3.js
      FieldName:                        listTasks
      Kind:                             PIPELINE
      PipelineConfig:
        Functions:
          - !GetAtt ListTasksFunction.FunctionId
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
      TypeName:                         Query
    DependsOn:
      -                                 TaskApiSchema
    Metadata:
      aws:cdk:path:                     AppsyncDynamodbStack/ListTasksResolver/Resource


Outputs:
  GraphQLAPIURL:
    Value:                              !GetAtt TaskApi.GraphQLUrl
  GraphQLAPIKey:
    Value:                              !GetAtt TaskApiDefaultApiKey.ApiKey
