Transform:                              AWS::Serverless-2016-10-31


Resources:

  ##
  ## LambdaApiStack / CounterTable / Resource
  ##

  CounterTable:
    Type:                               AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName:                id
          AttributeType:                S
      BillingMode:                      PAY_PER_REQUEST
      KeySchema:
        - AttributeName:                id
          KeyType:                      HASH
    DeletionPolicy:                     Delete
    UpdateReplacePolicy:                Delete

  ##
  ## LambdaApiStack / HelloFunctionLogGroup / Resource
  ##

  HelloFunctionLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      RetentionInDays:                  7
    DeletionPolicy:                     Delete
    UpdateReplacePolicy:                Delete

  ##
  ## LambdaApiStack / PythonHelloFunctionLogGroup / Resource
  ##

  PythonHelloFunctionLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      RetentionInDays:                  7
    DeletionPolicy:                     Delete
    UpdateReplacePolicy:                Delete

  ##
  ## LambdaApiStack / HelloFunction / Resource
  ##

  HelloFunction:
    Type:                               AWS::Serverless::Function
    Properties:
      InlineCode:                       |-
                                        exports.handler = async (event) => {
                                          console.log('Event:', JSON.stringify(event));
                                          return {
                                            statusCode: 200,
                                            body: JSON.stringify({ message: 'Hello World!' })
                                          };
                                        };
      Environment:
        Variables:
          TABLE_NAME: !Ref CounterTable
      Handler:                          index.handler
      LoggingConfig:
        LogGroup: !Ref HelloFunctionLogs
      Runtime:                          nodejs22.x
      Timeout:                          30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CounterTable
      Events:
        ApiGetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: GET
        ApiAnyProxy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

  ##
  ## LambdaApiStack / PythonHelloFunction / Resource
  ##

  PythonHelloFunction:
    Type:                               AWS::Serverless::Function
    Properties:
      InlineCode:                       |-
                                        import json
                                        
                                        def handler(event, context):
                                            print("Event:", json.dumps(event))
                                            return {
                                                "statusCode": 200,
                                                "body": json.dumps({"message": "Hello from Python!"})
                                            }
      Environment:
        Variables:
          TABLE_NAME: !Ref CounterTable
      Handler:                          index.handler
      LoggingConfig:
        LogGroup: !Ref PythonHelloFunctionLogs
      Runtime:                          python3.12
      Timeout:                          30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CounterTable
      Events:
        ApiGetPython:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /python
            Method: GET

  ##
  ## LambdaApiStack / AssetFunction / Resource
  ##

  AssetFunction:
    Type:                               AWS::Serverless::Function
    Properties:
      CodeUri:                          src/asset.d9b2ae48081978dc24db5de71f5a5f2d2a3210789924cf617d518e279c64636c
      Handler:                          index.handler
      MemorySize:                       128
      Runtime:                          nodejs22.x
      Timeout:                          10
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowMethods:
            - GET
          AllowOrigins:
            - "*"
    Metadata:
      aws:asset:path:                   asset.d9b2ae48081978dc24db5de71f5a5f2d2a3210789924cf617d518e279c64636c
      aws:asset:is-bundled:             false
      aws:asset:property:               Code

  ##
  ## LambdaApiStack / AssetFunction / LogGroup / Resource
  ##

  AssetFunctionLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      LogGroupName:                     !Sub /aws/lambda/${AssetFunction}
      RetentionInDays:                  731
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain

  ##
  ## LambdaApiStack / ApiGateway / Resource
  ##

  ApiGateway:
    Type:                               AWS::Serverless::Api
    Properties:
      Name:                             HelloApi
      StageName:                        prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        AllowMethods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"


Outputs:
  ApiGatewayEndpoint5AA8EC3A:
    Value:                              !Sub https://${ApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod/
  ApiUrl:
    Value:                              !Sub https://${ApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod/
  AssetFunctionUrl:
    Value:                              !GetAtt AssetFunctionUrl.FunctionUrl
