AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles and policies with complex conditions
Parameters:
  BucketName:
    Type: String
    Description: Target S3 bucket name referenced by policies
    Default: my-secure-bucket
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${BucketName}/*'
                Condition:
                  StringEquals:
                    s3:x-amz-server-side-encryption: AES256
                  IpAddress:
                    aws:SourceIp:
                      - 192.168.1.0/24
                      - 10.0.0.0/8
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub '${S3Bucket.Arn}/*'
              - !GetAtt S3Bucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
