Transform:                              AWS::Serverless-2016-10-31


Resources:

  ##
  ## AppsyncDynamodbStack / TasksTable / Resource
  ##

  TasksTable:
    Type:                               AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName:                id
          AttributeType:                S
      BillingMode:                      PAY_PER_REQUEST
      KeySchema:
        - AttributeName:                id
          KeyType:                      HASH
      TableName:                        tasks
    DeletionPolicy:                     Delete
    UpdateReplacePolicy:                Delete

  ##
  ## AppsyncDynamodbStack / TaskApi / Resource
  ##

  TaskApi:
    Type:                               AWS::Serverless::GraphQLApi
    Properties:
      Auth:
        Type:                           API_KEY
      Name:                             task-api
      SchemaInline:                     |-
                                        type Task {
                                          id: ID!
                                          title: String!
                                          description: String
                                          completed: Boolean!
                                          createdAt: AWSDateTime!
                                        }
                                        
                                        type Query {
                                          getTask(id: ID!): Task
                                          listTasks: [Task!]!
                                        }
                                        
                                        type Mutation {
                                          createTask(title: String!, description: String): Task!
                                          updateTask(id: ID!, title: String, description: String, completed: Boolean): Task!
                                          deleteTask(id: ID!): Task
                                        }
                                        
                                        schema {
                                          query: Query
                                          mutation: Mutation
                                        }
      DataSources:
        DynamoDb:
          TasksDataSource:
            TableName: !Ref TasksTable
            Region: !Ref AWS::Region
            ServiceRoleArn: !GetAtt TasksDataSourceRole.Arn
            Name: TasksDataSource
      Functions:
        GetTaskFunction:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: TasksDataSource
          Name: getTask
          CodeUri: src/GetTaskFunction/function.js
        ListTasksFunction:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: TasksDataSource
          Name: listTasks
          CodeUri: src/ListTasksFunction/function.js
      Resolvers:
        Query:
          GetTaskResolver:
            FieldName: getTask
            Pipeline:
              - GetTaskFunction
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            CodeUri: src/GetTaskResolver/resolver.js
          ListTasksResolver:
            FieldName: listTasks
            Pipeline:
              - ListTasksFunction
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            CodeUri: src/ListTasksResolver/resolver.js
      ApiKeys:
        TaskApiDefaultApiKey:
          ApiKeyId: TaskApiDefaultApiKey
      XrayEnabled:                      true

  ##
  ## AppsyncDynamodbStack / TaskApi / TasksDataSource / ServiceRole / Resource
  ##

  TasksDataSourceRole:
    Type:                               AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
        Version: '2012-10-17'

  ##
  ## AppsyncDynamodbStack / TaskApi / TasksDataSource / ServiceRole / DefaultPolicy / Resource
  ##

  ServiceRolePolicy:
    Type:                               AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - !GetAtt TasksTable.Arn
              - !Ref AWS::NoValue
        Version: '2012-10-17'
      PolicyName:                       ServiceRolePolicy
      Roles:
        - !Ref TasksDataSourceRole


Outputs:
  GraphQLAPIURL:
    Value:                              !GetAtt TaskApi.GraphQLUrl
  GraphQLAPIKey:
    Value:                              !GetAtt TaskApiTaskApiDefaultApiKey.ApiKey
