Parameters:
  BootstrapVersion:
    Type:                               AWS::SSM::Parameter::Value<String>
    Default:                            /cdk-bootstrap/hnb659fds/version
    Description:                        Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]


Resources:

  ##
  ## SamRefactorShowcaseStack / CommonLayer / Resource
  ##

  CommonLayer:
    Type:                               AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        -                               nodejs22.x
      Content:
        S3Bucket:                       !Sub cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key:                          d2f4d8af2cc22e4fe42b1558a85543a3964a5515f26257aecb49ad44df8e3d5d.zip
      Description:                      Shared utilities layer for SAM refactor showcases
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/CommonLayer/Resource

  ##
  ## SamRefactorShowcaseStack / OrdersTable / Resource
  ##

  OrdersTable:
    Type:                               AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName:                orderId
          AttributeType:                S
      KeySchema:
        - AttributeName:                orderId
          KeyType:                      HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled:     true
      ProvisionedThroughput:
        ReadCapacityUnits:              5
        WriteCapacityUnits:             5
      SSESpecification:
        SSEEnabled:                     true
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/OrdersTable/Resource

  ##
  ## SamRefactorShowcaseStack / OrdersHandler / ServiceRole / Resource
  ##

  OrdersHandlerRole:
    Type:                               AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:                     sts:AssumeRole
            Effect:                     Allow
            Principal:
              Service:                  lambda.amazonaws.com
        Version:                        '2012-10-17'
      ManagedPolicyArns:
        -                               !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/OrdersHandler/ServiceRole/Resource

  ##
  ## SamRefactorShowcaseStack / OrdersHandler / ServiceRole / DefaultPolicy / Resource
  ##

  ServiceRolePolicy:
    Type:                               AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              -                         dynamodb:BatchGetItem
              -                         dynamodb:BatchWriteItem
              -                         dynamodb:ConditionCheckItem
              -                         dynamodb:DeleteItem
              -                         dynamodb:DescribeTable
              -                         dynamodb:GetItem
              -                         dynamodb:GetRecords
              -                         dynamodb:GetShardIterator
              -                         dynamodb:PutItem
              -                         dynamodb:Query
              -                         dynamodb:Scan
              -                         dynamodb:UpdateItem
            Effect:                     Allow
            Resource:
              -                         !GetAtt OrdersTable.Arn
              -                         !Ref AWS::NoValue
        Version:                        '2012-10-17'
      PolicyName:                       ServiceRolePolicy
      Roles:
        -                               !Ref OrdersHandlerRole
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/OrdersHandler/ServiceRole/DefaultPolicy/Resource

  ##
  ## SamRefactorShowcaseStack / OrdersHandler / Resource
  ##

  OrdersHandler:
    Type:                               AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:                        |-
                                        exports.handler = async (event) => {
                                                  console.log('event', JSON.stringify(event));
                                                  return { statusCode: 200 };
                                                };
      Environment:
        Variables:
          TABLE_NAME: !Ref OrdersTable
      Handler:                          index.handler
      Layers:
        -                               !Ref CommonLayer
      Role:                             !GetAtt OrdersHandlerRole.Arn
      Runtime:                          nodejs22.x
    DependsOn:
      -                                 ServiceRolePolicy
      -                                 OrdersHandlerRole
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/OrdersHandler/Resource

  ##
  ## SamRefactorShowcaseStack / OrdersHandler / LogGroup / Resource
  ##

  OrdersHandlerLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      LogGroupName:                     !Sub /aws/lambda/${OrdersHandler}
      RetentionInDays:                  731
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/OrdersHandler/LogGroup/Resource

  ##
  ## SamRefactorShowcaseStack / DocDbStreamHandler / ServiceRole / Resource
  ##

  DocDbStreamHandlerRole:
    Type:                               AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version:                        '2012-10-17'
      ManagedPolicyArns:
        -                               !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/DocDbStreamHandler/ServiceRole/Resource

  ##
  ## SamRefactorShowcaseStack / DocDbStreamHandler / Resource
  ##

  DocDbStreamHandler:
    Type:                               AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:                        |-
                                        def handler(event, _context):
                                            print(event)
                                            return { 'statusCode': 200 }
      Handler:                          index.handler
      Role:                             !GetAtt DocDbStreamHandlerRole.Arn
      Runtime:                          python3.12
    DependsOn:
      -                                 DocDbStreamHandlerRole
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/DocDbStreamHandler/Resource

  ##
  ## SamRefactorShowcaseStack / DocDbStreamHandler / LogGroup / Resource
  ##

  DocDbStreamHandlerLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      LogGroupName:                     !Sub /aws/lambda/${DocDbStreamHandler}
      RetentionInDays:                  731
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/DocDbStreamHandler/LogGroup/Resource

  ##
  ## SamRefactorShowcaseStack / DocDbEventSource
  ##

  DocDbEventSource:
    Type:                               AWS::Lambda::EventSourceMapping
    Properties:
      DocumentDBEventSourceConfig:
        CollectionName:                 events
        DatabaseName:                   orders
        FullDocument:                   UpdateLookup
      EventSourceArn:                   arn:aws:docdb:us-east-1:123456789012:cluster:orders
      FunctionName:                     !Ref DocDbStreamHandler
      SourceAccessConfigurations:
        - Type:                         BASIC_AUTH
          URI: arn:aws:secretsmanager:us-east-1:123456789012:secret:docdb-creds
      StartingPosition:                 LATEST
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/DocDbEventSource

  ##
  ## SamRefactorShowcaseStack / DeviceRule
  ##

  DeviceRule:
    Type:                               AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Actions:
          - Lambda:
              FunctionArn: !GetAtt OrdersHandler.Arn
        RuleDisabled:                   false
        Sql:                            SELECT * FROM 'devices/+/events'
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/DeviceRule

  ##
  ## SamRefactorShowcaseStack / IotInvokePermission
  ##

  IotInvokePermission:
    Type:                               AWS::Lambda::Permission
    Properties:
      Action:                           lambda:InvokeFunction
      FunctionName:                     !Ref OrdersHandler
      Principal:                        iot.amazonaws.com
      SourceArn:                        !GetAtt DeviceRule.Arn
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/IotInvokePermission

  ##
  ## SamRefactorShowcaseStack / Users / PreSignUpCognito
  ##

  UsersPreSignUpCognito:
    Type:                               AWS::Lambda::Permission
    Properties:
      Action:                           lambda:InvokeFunction
      FunctionName:                     !GetAtt OrdersHandler.Arn
      Principal:                        cognito-idp.amazonaws.com
      SourceArn:                        !GetAtt Users.Arn
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/Users/PreSignUpCognito

  ##
  ## SamRefactorShowcaseStack / Users / PostConfirmationCognito
  ##

  UsersPostConfirmationCognito:
    Type:                               AWS::Lambda::Permission
    Properties:
      Action:                           lambda:InvokeFunction
      FunctionName:                     !GetAtt OrdersHandler.Arn
      Principal:                        cognito-idp.amazonaws.com
      SourceArn:                        !GetAtt Users.Arn
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/Users/PostConfirmationCognito

  ##
  ## SamRefactorShowcaseStack / Users / Resource
  ##

  Users:
    Type:                               AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_phone_number
            Priority: 1
          - Name: verified_email
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly:       true
      EmailVerificationMessage:         The verification code to your new account is {####}
      EmailVerificationSubject:         Verify your new account
      LambdaConfig:
        PostConfirmation:               !GetAtt OrdersHandler.Arn
        PreSignUp:                      !GetAtt OrdersHandler.Arn
      SmsVerificationMessage:           The verification code to your new account is {####}
      UserPoolName:                     refactor-showcase-users
      VerificationMessageTemplate:
        DefaultEmailOption:             CONFIRM_WITH_CODE
        EmailMessage:                   The verification code to your new account is {####}
        EmailSubject:                   Verify your new account
        SmsMessage:                     The verification code to your new account is {####}
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/Users/Resource

  ##
  ## SamRefactorShowcaseStack / HttpApiShell
  ##

  HttpApiShell:
    Type:                               AWS::ApiGatewayV2::Api
    Properties:
      Description:                      Placeholder HTTP API for SAM HttpApi folding
      Name:                             shell-api
      ProtocolType:                     HTTP
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/HttpApiShell

  ##
  ## SamRefactorShowcaseStack / HttpApiStage
  ##

  HttpApiStage:
    Type:                               AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:                            !Ref HttpApiShell
      AutoDeploy:                       true
      StageName:                        $default
    Metadata:
      aws:cdk:path:                     SamRefactorShowcaseStack/HttpApiStage
