Parameters:
  DocDbPassword:
    Type:                               String
    Description:                        Master user password for the sample DocDB cluster

    MinLength:                          8
    NoEcho:                             true


Transform:                              AWS::Serverless-2016-10-31


Resources:

  ##
  ## Fn
  ##

  Fn:
    Type:                               AWS::Serverless::Function
    Properties:
      InlineCode:                       |-
                                        exports.handler = async () => { return 'ok'; }
      Handler:                          index.handler
      Runtime:                          nodejs22.x
      Events:
        DocDbMapping:
          Type: DocumentDB
          Properties:
            Cluster: arn:aws:rds:us-east-1:123456789012:cluster:docdb-sample
            StartingPosition: LATEST
            SourceAccessConfigurations:
              - Type: BASIC_AUTH
                URI: arn:aws:secretsmanager:us-east-1:123456789012:secret:creds
            DatabaseName: appdb
        UserPoolPreSignUp:
          Type: Cognito
          Properties:
            UserPool: !Ref UserPool
            Trigger: PreSignUp

  ##
  ## Layer
  ##

  Layer:
    Type:                               AWS::Serverless::LayerVersion
    Properties:
      ContentUri:
        Bucket: assets
        Key: layer.zip
      Description:                      shared layer
      CompatibleRuntimes:
        - nodejs22.x

  ##
  ## Table
  ##

  Table:
    Type:                               AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Type: String
        Name: id
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName:                        sample-table

  ##
  ## HttpApi
  ##

  HttpApi:
    Type:                               AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: sample-http
        paths: {}

  ##
  ## IotRule
  ##

  IotRule:
    Type:                               AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Sql: SELECT * FROM 'topic'
        RuleDisabled: false
        Actions:
          - Lambda:
              FunctionArn: !GetAtt Fn.Arn

  ##
  ## InvokePerm
  ##

  InvokePerm:
    Type:                               AWS::Lambda::Permission
    Properties:
      FunctionName:                     !Ref Fn
      Principal:                        iot.amazonaws.com
      Action:                           lambda:InvokeFunction

  ##
  ## UserPool
  ##

  UserPool:
    Type:                               AWS::Cognito::UserPool
    Properties:                         {}

  ##
  ## DocDb
  ##

  DocDb:
    Type:                               AWS::DocDB::DBCluster
    Properties:
      MasterUsername:                   master
      MasterUserPassword:               !Ref DocDbPassword
