AWSTemplateFormatVersion:               '2010-09-09'
Description:                            Lambda event sources covering SQS, self-managed Kafka, and S3 notifications


Resources:

  ##
  ## LambdaFunction
  ##

  LambdaFunction:
    Type:                               AWS::Lambda::Function
    Properties:
      Handler:                          index.handler
      Runtime:                          python3.11
      Role:                             arn:aws:iam::123456789012:role/Dummy
      Code:
        ZipFile:                        |
                                        def handler(event, context):
                                            return {"statusCode": 200}

  ##
  ## Queue
  ##

  Queue:
    Type:                               AWS::SQS::Queue
    Properties:
      VisibilityTimeout:                30

  ##
  ## Stream
  ##

  Stream:
    Type:                               AWS::Kinesis::Stream
    Properties:
      ShardCount:                       1

  ##
  ## Bucket
  ##

  Bucket:
    Type:                               AWS::S3::Bucket
    Properties:
      BucketName:                       sample-event-bucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event:                      s3:ObjectCreated:*
            Function:                   !GetAtt LambdaFunction.Arn

  ##
  ## BucketInvokePermission
  ##

  BucketInvokePermission:
    Type:                               AWS::Lambda::Permission
    Properties:
      Action:                           lambda:InvokeFunction
      FunctionName:                     !Ref LambdaFunction
      Principal:                        s3.amazonaws.com
      SourceArn:                        !GetAtt Bucket.Arn
      SourceAccount:                    !Ref AWS::AccountId

  ##
  ## SqsMapping
  ##

  SqsMapping:
    Type:                               AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize:                        5
      EventSourceArn:                   !GetAtt Queue.Arn
      FunctionName:                     !Ref LambdaFunction
      MaximumBatchingWindowInSeconds:   10

  ##
  ## StreamMapping
  ##

  StreamMapping:
    Type:                               AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn:                   !GetAtt Stream.Arn
      FunctionName:                     !Ref LambdaFunction
      StartingPosition:                 LATEST
      BatchSize:                        100

  ##
  ## KafkaMapping
  ##

  KafkaMapping:
    Type:                               AWS::Lambda::EventSourceMapping
    Properties:
      FunctionName:                     !Ref LambdaFunction
      SelfManagedEventSource:
        Endpoints:
          KafkaBootstrapServers:
            -                           b-1.kafka.example.com:9092
            -                           b-2.kafka.example.com:9092
      Topics:
        -                               orders
      BatchSize:                        10
      MaximumBatchingWindowInSeconds:   5
      AmazonManagedKafkaEventSourceConfig:
        ConsumerGroupId:                group-a