AWSTemplateFormatVersion:               '2010-09-09'
Description:                            Demonstrating CloudFormation intrinsic functions


Parameters:
  Environment:
    Type:                               String
    Default:                            dev
    AllowedValues:
      -                                 dev
      -                                 staging
      -                                 prod


Mappings:
  RegionMap:
    us-east-1:
      AMI:                              ami-0123456789abcdef0
    us-west-2:
      AMI:                              ami-0abcdef0123456789


Conditions:
  IsProduction:                         !Equals
    -                                   !Ref Environment
    -                                   prod
  IsNotDev:                             !Not
    -                                   !Equals
      -                                 !Ref Environment
      -                                 dev


Resources:

  ##
  ## Instance
  ##

  Instance:
    Type:                               AWS::EC2::Instance
    Properties:
      ImageId:                          !FindInMap
        -                               RegionMap
        -                               !Ref AWS::Region
        -                               AMI
      InstanceType:                     !If
        -                               IsProduction
        -                               t3.large
        -                               t3.micro
      Tags:
        - Key:                          Name
          Value:                        !Sub ${AWS::StackName}-${Environment}-instance
        - Key:                          Environment
          Value:                        !Ref Environment

  ##
  ## SecurityGroup
  ##

  SecurityGroup:
    Type:                               AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:                 !Sub Security group for ${AWS::StackName} in ${Environment}
      SecurityGroupIngress:
        - IpProtocol:                   tcp
          FromPort:                     !If
            -                           IsProduction
            -                           443
            -                           80
          ToPort:                       !If
            -                           IsProduction
            -                           443
            -                           80
          CidrIp:                       0.0.0.0/0
      Tags:
        - Key:                          Name
          Value:                        !Sub ${AWS::StackName}-sg


Outputs:
  InstanceId:
    Description:                        ID of the EC2 instance
    Value:                              !Ref Instance
    Export:
      Name:                             !Sub ${AWS::StackName}-InstanceId
  SecurityGroupId:
    Description:                        ID of the security group
    Value:                              !GetAtt SecurityGroup.GroupId
    Condition:                          IsNotDev
