Parameters:
  DocDbPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Master user password for the sample DocDB cluster

Resources:
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  Fn:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt FnRole.Arn
      Code:
        ZipFile: exports.handler = async () => { return 'ok'; }
  Layer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: assets
        S3Key: layer.zip
      Description: shared layer
      CompatibleRuntimes:
        - nodejs22.x
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: sample-table
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Body:
        openapi: 3.0.1
        info:
          title: sample-http
        paths: {}
  HttpStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: $default
  IotRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Sql: "SELECT * FROM 'topic'"
        RuleDisabled: false
        Actions:
          - Lambda:
              FunctionArn: !GetAtt Fn.Arn
  InvokePerm:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Fn
      Principal: iot.amazonaws.com
      Action: lambda:InvokeFunction
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      LambdaConfig:
        PreSignUp: !Ref Fn
  DocDb:
    Type: AWS::DocDB::DBCluster
    Properties:
      MasterUsername: master
      MasterUserPassword: !Ref DocDbPassword
  DocDbMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: arn:aws:rds:us-east-1:123456789012:cluster:docdb-sample
      FunctionName: !Ref Fn
      StartingPosition: LATEST
      SourceAccessConfigurations:
        - Type: BASIC_AUTH
          URI: arn:aws:secretsmanager:us-east-1:123456789012:secret:creds
      DocumentDBEventSourceConfig:
        DatabaseName: appdb
