AWSTemplateFormatVersion:               '2010-09-09'
Description:                            Lambda event sources covering SQS, self-managed Kafka, and S3 notifications
Transform:                              AWS::Serverless-2016-10-31


Resources:

  ##
  ## LambdaFunction
  ##

  LambdaFunction:
    Type:                               AWS::Serverless::Function
    Properties:
      InlineCode:                       |-
                                        def handler(event, context):
                                            return {"statusCode": 200}
      Handler:                          index.handler
      Runtime:                          python3.11
      Role:                             arn:aws:iam::123456789012:role/Dummy
      Events:
        SqsMapping:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
            MaximumBatchingWindowInSeconds: 10
            BatchSize: 5
        StreamMapping:
          Type: Kinesis
          Properties:
            Stream: !GetAtt Stream.Arn
            StartingPosition: LATEST
            BatchSize: 100
        Bucket:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events:
              - s3:ObjectCreated:*

  ##
  ## Queue
  ##

  Queue:
    Type:                               AWS::SQS::Queue
    Properties:
      VisibilityTimeout:                30

  ##
  ## Stream
  ##

  Stream:
    Type:                               AWS::Kinesis::Stream
    Properties:
      ShardCount:                       1

  ##
  ## Bucket
  ##

  Bucket:
    Type:                               AWS::S3::Bucket
    Properties:
      BucketName:                       sample-event-bucket

  ##
  ## KafkaMapping
  ##

  KafkaMapping:
    Type:                               AWS::Lambda::EventSourceMapping
    Properties:
      FunctionName:                     !Ref LambdaFunction
      SelfManagedEventSource:
        Endpoints:
          KafkaBootstrapServers:
            - b-1.kafka.example.com:9092
            - b-2.kafka.example.com:9092
      Topics:
        - orders
      BatchSize:                        10
      MaximumBatchingWindowInSeconds:   5
      AmazonManagedKafkaEventSourceConfig:
        ConsumerGroupId: group-a
