Resources:

  ##
  ## S3CloudFrontStack / WebsiteBucket / Resource
  ##

  WebsiteBucket:
    Type:                               AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm:             AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls:                true
        BlockPublicPolicy:              true
        IgnorePublicAcls:               true
        RestrictPublicBuckets:          true
      WebsiteConfiguration:
        ErrorDocument:                  error.html
        IndexDocument:                  index.html
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain

  ##
  ## S3CloudFrontStack / WebsiteBucket / Policy / Resource
  ##

  WebsiteBucketPolicy:
    Type:                               AWS::S3::BucketPolicy
    Properties:
      Bucket:                           !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Action:                     s3:GetObject
            Condition:
              StringEquals:
                AWS:SourceArn:          !Sub arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${Distribution}
            Effect:                     Allow
            Principal:
              Service:                  cloudfront.amazonaws.com
            Resource:                   !Sub ${WebsiteBucket.Arn}/*
        Version:                        '2012-10-17'

  ##
  ## S3CloudFrontStack / LogsBucket / Resource
  ##

  LogsBucket:
    Type:                               AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm:             AES256
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays:           30
            Id:                         delete-old-logs
            Status:                     Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls:                true
        BlockPublicPolicy:              true
        IgnorePublicAcls:               true
        RestrictPublicBuckets:          true
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain

  ##
  ## S3CloudFrontStack / WebACL
  ##

  WebACL:
    Type:                               AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow:                          {}
      Rules:
        - Action:
            Block:                      {}
          Name:                         RateLimitRule
          Priority:                     1
          Statement:
            RateBasedStatement:
              AggregateKeyType:         IP
              Limit:                    2000
          VisibilityConfig:
            CloudWatchMetricsEnabled:   true
            MetricName:                 RateLimitRule
            SampledRequestsEnabled:     true
        - Action:
            Block:                      {}
          Name:                         GeoBlockRule
          Priority:                     2
          Statement:
            GeoMatchStatement:
              CountryCodes:
                -                       CN
                -                       RU
                -                       KP
          VisibilityConfig:
            CloudWatchMetricsEnabled:   true
            MetricName:                 GeoBlockRule
            SampledRequestsEnabled:     true
      Scope:                            CLOUDFRONT
      VisibilityConfig:
        CloudWatchMetricsEnabled:       true
        MetricName:                     WebACL
        SampledRequestsEnabled:         true

  ##
  ## S3CloudFrontStack / Distribution / Origin1 / S3OriginAccessControl / Resource
  ##

  Origin1S3OriginAccessControl:
    Type:                               AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name:                           S3CloudFrontStackDistributioOrigin1S3OriginAccessControl1DA14239
        OriginAccessControlOriginType:  s3
        SigningBehavior:                always
        SigningProtocol:                sigv4

  ##
  ## S3CloudFrontStack / Distribution / Resource
  ##

  Distribution:
    Type:                               AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment:                        CDN for S3 static website
        CustomErrorResponses:
          - ErrorCode:                  404
            ResponseCode:               404
            ResponsePagePath:           /error.html
        DefaultCacheBehavior:
          AllowedMethods:
            -                           GET
            -                           HEAD
            -                           OPTIONS
          CachePolicyId:                658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress:                     true
          TargetOriginId:               S3CloudFrontStackDistributionOrigin109D0460A
          ViewerProtocolPolicy:         redirect-to-https
        DefaultRootObject:              index.html
        Enabled:                        true
        HttpVersion:                    http2and3
        IPV6Enabled:                    true
        Logging:
          Bucket:                       !GetAtt LogsBucket.RegionalDomainName
          Prefix:                       distribution-logs
        Origins:
          - DomainName:                 !GetAtt WebsiteBucket.RegionalDomainName
            Id:                         S3CloudFrontStackDistributionOrigin109D0460A
            OriginAccessControlId:      !GetAtt Origin1S3OriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity:     ''
        PriceClass:                     PriceClass_100
        WebACLId:                       !GetAtt WebACL.Arn


Outputs:
  DistributionDomainName:
    Value:                              !GetAtt Distribution.DomainName
  BucketName:
    Value:                              !Ref WebsiteBucket
