AWSTemplateFormatVersion:               '2010-09-09'
Description:                            Template showcasing various parameter types and output configurations


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default:                      Network Configuration
        Parameters:
          -                             VpcCIDR
          -                             PublicSubnetCIDR
      - Label:
          default:                      Instance Configuration
        Parameters:
          -                             InstanceType
          -                             KeyName


Parameters:
  VpcCIDR:
    Type:                               String
    Description:                        CIDR block for the VPC
    Default:                            10.0.0.0/16
    AllowedPattern:                     ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription:              Must be a valid CIDR block
  PublicSubnetCIDR:
    Type:                               String
    Description:                        CIDR block for the public subnet
    Default:                            10.0.1.0/24
  InstanceType:
    Type:                               String
    Description:                        EC2 instance type
    Default:                            t3.micro
    AllowedValues:
      -                                 t3.nano
      -                                 t3.micro
      -                                 t3.small
      -                                 t3.medium
  KeyName:
    Type:                               AWS::EC2::KeyPair::KeyName
    Description:                        Name of an existing EC2 KeyPair
  DBPassword:
    Type:                               String
    Description:                        Database password
    MinLength:                          8
    MaxLength:                          128
    NoEcho:                             true
  AlarmEmail:
    Type:                               String
    Description:                        Email address for CloudWatch alarms
    AllowedPattern:                     ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
  BackupRetention:
    Type:                               Number
    Description:                        Number of days to retain backups
    Default:                            7
    MinValue:                           1
    MaxValue:                           365
  EnableMonitoring:
    Type:                               String
    Description:                        Enable CloudWatch monitoring
    Default:                            "true"
    AllowedValues:
      -                                 "true"
      -                                 "false"
  TagList:
    Type:                               CommaDelimitedList
    Description:                        List of tag keys to apply
    Default:                            Environment,Application,Owner
  SSMParameter:
    Type:                               AWS::SSM::Parameter::Value<String>
    Default:                            /myapp/config/version
    Description:                        SSM parameter containing configuration


Resources:

  ##
  ## VPC
  ##

  VPC:
    Type:                               AWS::EC2::VPC
    Properties:
      CidrBlock:                        !Ref VpcCIDR
      EnableDnsHostnames:               true
      Tags:
        - Key:                          Name
          Value:                        !Sub ${AWS::StackName}-vpc

  ##
  ## PublicSubnet
  ##

  PublicSubnet:
    Type:                               AWS::EC2::Subnet
    Properties:
      VpcId:                            !Ref VPC
      CidrBlock:                        !Ref PublicSubnetCIDR
      MapPublicIpOnLaunch:              true
      AvailabilityZone:                 !Select
        -                               0
        -                               !GetAZs
      Tags:
        - Key:                          Name
          Value:                        !Sub ${AWS::StackName}-public-subnet

  ##
  ## Instance
  ##

  Instance:
    Type:                               AWS::EC2::Instance
    Properties:
      InstanceType:                     !Ref InstanceType
      KeyName:                          !Ref KeyName
      ImageId:                          ami-12345678
      NetworkInterfaces:
        - DeviceIndex:                  0
          AssociatePublicIpAddress:     true
          SubnetId:                     !Ref PublicSubnet

  ##
  ## MonitoringRole
  ##

  MonitoringRole:
    Type:                               AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version:                        '2012-10-17'
        Statement:
          - Effect:                     Allow
            Principal:
              Service:                  lambda.amazonaws.com
            Action:                     sts:AssumeRole
      ManagedPolicyArns:
        -                               arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ##
  ## MonitoringFunction
  ##

  MonitoringFunction:
    Type:                               AWS::Lambda::Function
    Properties:
      Runtime:                          python3.11
      Handler:                          index.handler
      Role:                             !GetAtt MonitoringRole.Arn
      Code:
        ZipFile:                        |
                                        def handler(event, context):
                                            return {"statusCode": 200}
      Environment:
        Variables:
          DB_PASSWORD: !Ref DBPassword
          ALARM_EMAIL: !Ref AlarmEmail
          BACKUP_RETENTION_DAYS: !Sub ${BackupRetention}
          ENABLE_MONITORING: !Ref EnableMonitoring
          TAG_KEYS: !Join
            - ','
            - !Ref TagList
          CONFIG_PARAM: !Ref SSMParameter


Outputs:
  VpcId:
    Description:                        ID of the VPC
    Value:                              !Ref VPC
    Export:
      Name:                             !Sub ${AWS::StackName}:VpcId
  VpcCidr:
    Description:                        CIDR block of the VPC
    Value:                              !GetAtt VPC.CidrBlock
  StackName:
    Description:                        Name of this stack
    Value:                              !Ref AWS::StackName
  PublicSubnetId:
    Description:                        ID of the public subnet
    Value:                              !Ref PublicSubnet
  Region:
    Description:                        AWS Region
    Value:                              !Ref AWS::Region
  AccountId:
    Description:                        AWS Account ID
    Value:                              !Ref AWS::AccountId
