AWSTemplateFormatVersion:               '2010-09-09'
Description:                            A simple S3 bucket with lifecycle configuration


Parameters:
  BucketName:
    Type:                               String
    Description:                        Name for the S3 bucket
    Default:                            my-example-bucket
  RetentionDays:
    Type:                               Number
    Description:                        Number of days to retain objects
    Default:                            30


Resources:

  ##
  ## S3Bucket
  ##

  S3Bucket:
    Type:                               AWS::S3::Bucket
    Properties:
      BucketName:                       !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id:                         DeleteOldObjects
            Status:                     Enabled
            ExpirationInDays:           !Ref RetentionDays
      Tags:
        - Key:                          Environment
          Value:                        Production
        - Key:                          Owner
          Value:                        DevOps


Outputs:
  BucketArn:
    Description:                        ARN of the S3 bucket
    Value:                              !GetAtt S3Bucket.Arn
  BucketName:
    Description:                        Name of the S3 bucket
    Value:                              !Ref S3Bucket
