Transform:                              AWS::Serverless-2016-10-31


Resources:

  ##
  ## SamRefactorShowcaseStack / CommonLayer / Resource
  ##

  CommonLayer:
    Type:                               AWS::Serverless::LayerVersion
    Properties:
      ContentUri:                       src/asset.d2f4d8af2cc22e4fe42b1558a85543a3964a5515f26257aecb49ad44df8e3d5d
      Description:                      Shared utilities layer for SAM refactor showcases
      CompatibleRuntimes:
        -                               nodejs22.x
    Metadata:
      aws:asset:path:                   asset.d2f4d8af2cc22e4fe42b1558a85543a3964a5515f26257aecb49ad44df8e3d5d
      aws:asset:is-bundled:             false
      aws:asset:property:               Content

  ##
  ## SamRefactorShowcaseStack / OrdersTable / Resource
  ##

  OrdersTable:
    Type:                               AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Type:                           String
        Name:                           orderId
      ProvisionedThroughput:
        ReadCapacityUnits:              5
        WriteCapacityUnits:             5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled:     true
      SSESpecification:
        SSEEnabled:                     true
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain

  ##
  ## SamRefactorShowcaseStack / OrdersHandler / Resource
  ##

  OrdersHandler:
    Type:                               AWS::Serverless::Function
    Properties:
      InlineCode:                       |-
                                        exports.handler = async (event) => {
                                                  console.log('event', JSON.stringify(event));
                                                  return { statusCode: 200 };
                                                };
      Environment:
        Variables:
          TABLE_NAME: !Ref OrdersTable
      Handler:                          index.handler
      Layers:
        - !Ref CommonLayer
      Runtime:                          nodejs22.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        UsersPostConfirmation:
          Type: Cognito
          Properties:
            UserPool: !Ref Users
            Trigger: PostConfirmation
        UsersPreSignUp:
          Type: Cognito
          Properties:
            UserPool: !Ref Users
            Trigger: PreSignUp

  ##
  ## SamRefactorShowcaseStack / OrdersHandler / LogGroup / Resource
  ##

  OrdersHandlerLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      LogGroupName:                     !Sub /aws/lambda/${OrdersHandler}
      RetentionInDays:                  731
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain

  ##
  ## SamRefactorShowcaseStack / DocDbStreamHandler / Resource
  ##

  DocDbStreamHandler:
    Type:                               AWS::Serverless::Function
    Properties:
      InlineCode:                       |-
                                        def handler(event, _context):
                                            print(event)
                                            return { 'statusCode': 200 }
      Handler:                          index.handler
      Runtime:                          python3.12
      Events:
        DocDbEventSource:
          Type: DocumentDB
          Properties:
            Cluster: arn:aws:docdb:us-east-1:123456789012:cluster:orders
            StartingPosition: LATEST
            SourceAccessConfigurations:
              - Type: BASIC_AUTH
                URI: arn:aws:secretsmanager:us-east-1:123456789012:secret:docdb-creds
            DatabaseName: orders
            CollectionName: events
            FullDocument: UpdateLookup

  ##
  ## SamRefactorShowcaseStack / DocDbStreamHandler / LogGroup / Resource
  ##

  DocDbStreamHandlerLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      LogGroupName:                     !Sub /aws/lambda/${DocDbStreamHandler}
      RetentionInDays:                  731
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain

  ##
  ## SamRefactorShowcaseStack / DeviceRule
  ##

  DeviceRule:
    Type:                               AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Actions:
          - Lambda:
              FunctionArn: !GetAtt OrdersHandler.Arn
        RuleDisabled: false
        Sql: SELECT * FROM 'devices/+/events'

  ##
  ## SamRefactorShowcaseStack / IotInvokePermission
  ##

  IotInvokePermission:
    Type:                               AWS::Lambda::Permission
    Properties:
      Action:                           lambda:InvokeFunction
      FunctionName:                     !Ref OrdersHandler
      Principal:                        iot.amazonaws.com
      SourceArn:                        !GetAtt DeviceRule.Arn

  ##
  ## SamRefactorShowcaseStack / Users / PreSignUpCognito
  ##

  UsersPreSignUpCognito:
    Type:                               AWS::Lambda::Permission
    Properties:
      Action:                           lambda:InvokeFunction
      FunctionName:                     !GetAtt OrdersHandler.Arn
      Principal:                        cognito-idp.amazonaws.com
      SourceArn:                        !GetAtt Users.Arn

  ##
  ## SamRefactorShowcaseStack / Users / PostConfirmationCognito
  ##

  UsersPostConfirmationCognito:
    Type:                               AWS::Lambda::Permission
    Properties:
      Action:                           lambda:InvokeFunction
      FunctionName:                     !GetAtt OrdersHandler.Arn
      Principal:                        cognito-idp.amazonaws.com
      SourceArn:                        !GetAtt Users.Arn

  ##
  ## SamRefactorShowcaseStack / Users / Resource
  ##

  Users:
    Type:                               AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_phone_number
            Priority: 1
          - Name: verified_email
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      EmailVerificationMessage:         The verification code to your new account is {####}
      EmailVerificationSubject:         Verify your new account
      SmsVerificationMessage:           The verification code to your new account is {####}
      UserPoolName:                     refactor-showcase-users
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain

  ##
  ## SamRefactorShowcaseStack / HttpApiShell
  ##

  HttpApiShell:
    Type:                               AWS::Serverless::HttpApi
    Properties:
      Name:                             shell-api
      Description:                      Placeholder HTTP API for SAM HttpApi folding
