Parameters:
  BootstrapVersion:
    Type:                               AWS::SSM::Parameter::Value<String>
    Default:                            /cdk-bootstrap/hnb659fds/version
    Description:                        Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]


Resources:

  ##
  ## StepFunctionsStack / OrderNotificationTopic / Resource
  ##

  OrderNotificationTopic:
    Type:                               AWS::SNS::Topic
    Properties:
      DisplayName:                      Order Processing Notifications
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/OrderNotificationTopic/Resource

  ##
  ## StepFunctionsStack / ValidateOrderFunction / ServiceRole / Resource
  ##

  ValidateOrderFunctionRole:
    Type:                               AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:                     sts:AssumeRole
            Effect:                     Allow
            Principal:
              Service:                  lambda.amazonaws.com
        Version:                        '2012-10-17'
      ManagedPolicyArns:
        -                               !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ValidateOrderFunction/ServiceRole/Resource

  ##
  ## StepFunctionsStack / ValidateOrderFunction / Resource
  ##

  ValidateOrderFunction:
    Type:                               AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:                        |2-
                                        
                                        exports.handler = async (event) => {
                                          return { isValid: true };
                                        };
      Handler:                          index.handler
      Role:                             !GetAtt ValidateOrderFunctionRole.Arn
      Runtime:                          nodejs22.x
    DependsOn:
      -                                 ValidateOrderFunctionRole
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ValidateOrderFunction/Resource

  ##
  ## StepFunctionsStack / ValidateOrderFunction / LogGroup / Resource
  ##

  ValidateOrderFunctionLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      LogGroupName:                     !Sub /aws/lambda/${ValidateOrderFunction}
      RetentionInDays:                  731
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ValidateOrderFunction/LogGroup/Resource

  ##
  ## StepFunctionsStack / ProcessPaymentFunction / ServiceRole / Resource
  ##

  ProcessPaymentFunctionRole:
    Type:                               AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version:                        '2012-10-17'
      ManagedPolicyArns:
        -                               !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ProcessPaymentFunction/ServiceRole/Resource

  ##
  ## StepFunctionsStack / ProcessPaymentFunction / Resource
  ##

  ProcessPaymentFunction:
    Type:                               AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:                        |2-
                                        
                                        exports.handler = async (event) => {
                                          return { paymentSuccess: true };
                                        };
      Handler:                          index.handler
      Role:                             !GetAtt ProcessPaymentFunctionRole.Arn
      Runtime:                          nodejs22.x
    DependsOn:
      -                                 ProcessPaymentFunctionRole
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ProcessPaymentFunction/Resource

  ##
  ## StepFunctionsStack / ProcessPaymentFunction / LogGroup / Resource
  ##

  ProcessPaymentFunctionLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      LogGroupName:                     !Sub /aws/lambda/${ProcessPaymentFunction}
      RetentionInDays:                  731
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ProcessPaymentFunction/LogGroup/Resource

  ##
  ## StepFunctionsStack / ShipOrderFunction / ServiceRole / Resource
  ##

  ShipOrderFunctionRole:
    Type:                               AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version:                        '2012-10-17'
      ManagedPolicyArns:
        -                               !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ShipOrderFunction/ServiceRole/Resource

  ##
  ## StepFunctionsStack / ShipOrderFunction / Resource
  ##

  ShipOrderFunction:
    Type:                               AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:                        |2-
                                        
                                        exports.handler = async (event) => {
                                          return { shipped: true };
                                        };
      Handler:                          index.handler
      Role:                             !GetAtt ShipOrderFunctionRole.Arn
      Runtime:                          nodejs22.x
    DependsOn:
      -                                 ShipOrderFunctionRole
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ShipOrderFunction/Resource

  ##
  ## StepFunctionsStack / ShipOrderFunction / LogGroup / Resource
  ##

  ShipOrderFunctionLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      LogGroupName:                     !Sub /aws/lambda/${ShipOrderFunction}
      RetentionInDays:                  731
    DeletionPolicy:                     Retain
    UpdateReplacePolicy:                Retain
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ShipOrderFunction/LogGroup/Resource

  ##
  ## StepFunctionsStack / ProcessOrderStateMachineLogGroup / Resource
  ##

  ProcessOrderStateMachineLogs:
    Type:                               AWS::Logs::LogGroup
    Properties:
      RetentionInDays:                  731
    DeletionPolicy:                     Delete
    UpdateReplacePolicy:                Delete
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ProcessOrderStateMachineLogGroup/Resource

  ##
  ## StepFunctionsStack / ProcessOrderStateMachine / Role / Resource
  ##

  ProcessOrderStateMachineRole:
    Type:                               AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
        Version:                        '2012-10-17'
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ProcessOrderStateMachine/Role/Resource

  ##
  ## StepFunctionsStack / ProcessOrderStateMachine / Role / DefaultPolicy / Resource
  ##

  RolePolicy:
    Type:                               AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - !GetAtt ProcessPaymentFunction.Arn
              - !GetAtt ShipOrderFunction.Arn
              - !GetAtt ValidateOrderFunction.Arn
              - !Sub ${ProcessPaymentFunction.Arn}:*
              - !Sub ${ShipOrderFunction.Arn}:*
              - !Sub ${ValidateOrderFunction.Arn}:*
          - Action: sns:Publish
            Effect: Allow
            Resource: !Ref OrderNotificationTopic
          - Action:
              - logs:CreateLogDelivery
              - logs:DeleteLogDelivery
              - logs:DescribeLogGroups
              - logs:DescribeResourcePolicies
              - logs:GetLogDelivery
              - logs:ListLogDeliveries
              - logs:PutResourcePolicy
              - logs:UpdateLogDelivery
            Effect: Allow
            Resource: "*"
        Version:                        '2012-10-17'
      PolicyName:                       RolePolicy
      Roles:
        -                               !Ref ProcessOrderStateMachineRole
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ProcessOrderStateMachine/Role/DefaultPolicy/Resource

  ##
  ## StepFunctionsStack / ProcessOrderStateMachine / Resource
  ##

  ProcessOrderStateMachine:
    Type:                               AWS::StepFunctions::StateMachine
    Properties:
      LoggingConfiguration:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt ProcessOrderStateMachineLogs.Arn
        IncludeExecutionData:           true
        Level:                          ALL
      RoleArn:                          !GetAtt ProcessOrderStateMachineRole.Arn
      StateMachineName:                 ProcessOrderStateMachine
      StateMachineType:                 STANDARD
      Definition:
        StartAt:                        ValidateOrder
        States:
          ValidateOrder:
            Next: OrderValid?
            Retry:
              - ErrorEquals:
                  - Lambda.ClientExecutionTimeoutException
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
            Type: Task
            Resource: !Sub arn:${AWS::Partition}:states:::lambda:invoke
            Parameters:
              FunctionName: !GetAtt ValidateOrderFunction.Arn
              Payload.$: $
          OrderValid?:
            Type: Choice
            Choices:
              - Variable: $.Payload.isValid
                BooleanEquals: true
                Next: ProcessPayment
            Default: OrderFailed
          OrderFailed:
            End: true
            Type: Task
            Resource: !Sub arn:${AWS::Partition}:states:::sns:publish
            Parameters:
              TopicArn: !Ref OrderNotificationTopic
              Message: Order validation failed
          ProcessPayment:
            Next: PaymentSuccessful?
            Retry:
              - ErrorEquals:
                  - Lambda.ClientExecutionTimeoutException
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
            Type: Task
            Resource: !Sub arn:${AWS::Partition}:states:::lambda:invoke
            Parameters:
              FunctionName: !GetAtt ProcessPaymentFunction.Arn
              Payload.$: $
          PaymentSuccessful?:
            Type: Choice
            Choices:
              - Variable: $.Payload.paymentSuccess
                BooleanEquals: true
                Next: ShipOrder
            Default: PaymentFailed
          PaymentFailed:
            End: true
            Type: Task
            Resource: !Sub arn:${AWS::Partition}:states:::sns:publish
            Parameters:
              TopicArn: !Ref OrderNotificationTopic
              Message: Payment processing failed
          ShipOrder:
            Next: NotifySuccess
            Retry:
              - ErrorEquals:
                  - Lambda.ClientExecutionTimeoutException
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
            Type: Task
            Resource: !Sub arn:${AWS::Partition}:states:::lambda:invoke
            Parameters:
              FunctionName: !GetAtt ShipOrderFunction.Arn
              Payload.$: $
          NotifySuccess:
            End: true
            Type: Task
            Resource: !Sub arn:${AWS::Partition}:states:::sns:publish
            Parameters:
              TopicArn: !Ref OrderNotificationTopic
              Message: Order processed successfully
    DependsOn:
      -                                 RolePolicy
      -                                 ProcessOrderStateMachineRole
    DeletionPolicy:                     Delete
    UpdateReplacePolicy:                Delete
    Metadata:
      aws:cdk:path:                     StepFunctionsStack/ProcessOrderStateMachine/Resource


Outputs:
  StateMachineArn:
    Value:                              !Ref ProcessOrderStateMachine
